### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by capaj** [flying-sheep/babel-plugin-transform-react-createelement-to-jsx#8]
Getting this with 
```
    "@babel/cli": "^7.2.3",
    "@babel/core": "^7.3.3",
```
Trying to convert source file https://github.com/capaj/react-datetime/blob/master/src/YearsView.js

```
capaj@capaj-i7-4771:~/git_projects/react-datetime$ npx babel --plugins transform-react-createelement-to-jsx src/YearsView.js 
RangeError: Maximum call stack size exceeded
    at baseClone (/home/capaj/git_projects/react-datetime/node_modules/@babel/types/node_modules/lodash/_baseClone.js:1:1)
    at clone (/home/capaj/git_projects/react-datetime/node_modules/@babel/types/node_modules/lodash/clone.js:33:10)
    at keys.forEach.key (/home/capaj/git_projects/react-datetime/node_modules/@babel/types/lib/builders/builder.js:40:55)
    at Array.forEach (<anonymous>)
    at builder (/home/capaj/git_projects/react-datetime/node_modules/@babel/types/lib/builders/builder.js:36:8)
    at Object.MemberExpression (/home/capaj/git_projects/react-datetime/node_modules/@babel/types/lib/builders/generated/index.js:357:31)
    at id.split.map.reduce (/home/capaj/git_projects/react-datetime/node_modules/@babel/plugin-transform-react-jsx/lib/index.js:59:113)
    at Array.reduce (<anonymous>)
    at /home/capaj/git_projects/react-datetime/node_modules/@babel/plugin-transform-react-jsx/lib/index.js:59:70
    at Object.post (/home/capaj/git_projects/react-datetime/node_modules/@babel/plugin-transform-react-jsx/lib/index.js:75:47)
```

**Comment by flying-sheep** [comment]
hmm, works for me.

```console
$ wget https://raw.githubusercontent.com/capaj/react-datetime/master/src/YearsView.js
$ npm run build
$ npx babel --plugins ./lib YearsView.js
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _react = _interopRequireDefault(require("react"));

var _createReactClass = _interopRequireDefault(require("create-react-class"));

var _reactOnclickoutside = _interopRequireDefault(require("@capaj/react-onclickoutside"));

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

var DateTimePickerYears = (0, _reactOnclickoutside.default)((0, _createReactClass.default)({
  render: function render() {
    var year = parseInt(this.props.viewDate.year() / 10, 10) * 10;
    return <div className='rdtYears'>{[<table key='a'><thead><tr>{[<th key='prev' className='rdtPrev' onClick={this.props.subtractTime(10, 'years')}><span>‹</span></th>, <th key='year' className='rdtSwitch' onClick={this.props.showView('years')} colSpan={2}>{"".concat(year, "-").concat(year + 9)}</th>, <th key='next' className='rdtNext' onClick={this.props.addTime(10, 'years')}><span>›</span></th>]}</tr></thead></table>, <table key='years'><tbody>{this.renderYears(year)}</tbody></table>]}</div>;
  },
  ...
};

...
```

can you give me a reproducible example as a sequence of shell commands?

maybe some .babelrc or something interferes

**Comment by capaj** [comment]
works flawlessly when I use `--no-babelrc`. Thanks

**Comment by flying-sheep** [comment]
ah! happy my hunch has helped here!
